@startuml
'https://plantuml.com/class-diagram

interface Dao {
    + getAllData():ArrayList<Player>
    + writeAllData(ArrayList<Player> L):void
    + writeOne(String name, int score):void
    + printAll():void
    + deleteAll():void
    + deleteOne(int rank):void
}
Dao <|... ScoreDao
class ScoreDao{
    + getAllData():ArrayList<Player>
    + writeAllData(ArrayList<Player> L):void
    + writeOne(String name, int score):void
    + printAll():void
    + deleteAll():void
    + deleteOne(int rank):void
}
class Player
{
    - Name:String
    - Score:int
    + Player(String Name, int Score)
    + compareTo(Object o):int
    + toString():String

}
ScoreDao -left-> Player
class Game
{
}
Game ..right.> Dao

@enduml